### ISSUE TITLE
error TS2307: Cannot find module 'xxx' but it is a peer dependency..

### ISSUE THREAD

**Issue by onurcskun** [callstack/react-native-builder-bob#107]
## How to fix cannot find module which is peerDep ?
I want to publish my library but when `bob build` is run it gives the error:
`error TS2307: Cannot find module 'xxx' or its corresponding type declarations.`

**Comment by mattijsf** [comment]
I have the same since 2 days. It worked fine before. It occurs both locally and on CI.

System: macOS
Node: v14.15.0
NPM: 6.14.8

Log:
```
npm ERR! prepareGitDep > react-native-image-picker@2.3.1 prepare /Users/mattijs/.npm/_cacache/tmp/git-clone-0b18cdbe
npm ERR! prepareGitDep > bob build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep ℹ Building target commonjs
npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/commonjs
npm ERR! prepareGitDep ℹ Compiling 4 files in src with babel
npm ERR! prepareGitDep ✓ Wrote files to lib/commonjs
npm ERR! prepareGitDep ℹ Building target module
npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/module
npm ERR! prepareGitDep ℹ Compiling 4 files in src with babel
npm ERR! prepareGitDep ✓ Wrote files to lib/module
npm ERR! prepareGitDep ℹ Building target typescript
npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/typescript
npm ERR! prepareGitDep ℹ Generating type definitions with tsc
npm ERR! prepareGitDep ✖ Errors found when building definition files:
npm ERR! prepareGitDep node_modules/@types/react/index.d.ts:38:22 - error TS2307: Cannot find module 'csstype' or its corresponding type declarations.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 38 import * as CSS from 'csstype';
npm ERR! prepareGitDep                         ~~~~~~~~~
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Found 1 error.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--also=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm ERR! prepareGitDep npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! prepareGitDep bob build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep build files for publishing
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Options:
npm ERR! prepareGitDep   --help     Show help                                                 [boolean]
npm ERR! prepareGitDep   --version  Show version number                                       [boolean]
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Error: Failed to build definition files.
npm ERR! prepareGitDep     at build (/Users/mattijs/.npm/_cacache/tmp/git-clone-0b18cdbe/node_modules/@react-native-community/bob/lib/targets/typescript.js:77:11)
npm ERR! prepareGitDep     at async Object.handler (/Users/mattijs/.npm/_cacache/tmp/git-clone-0b18cdbe/node_modules/@react-native-community/bob/lib/cli.js:299:9)
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! react-native-image-picker@2.3.1 prepare: `bob build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the react-native-image-picker@2.3.1 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/mattijs/.npm/_logs/2020-11-21T16_47_26_698Z-debug.log
```

**Comment by onurcskun** [comment]
@mattijsf hi mate, i solved my problem with adding that package to devDepend..

**Comment by mattijsf** [comment]
It's a bit odd though that this only happened over time. I'm not sure if this is a bug of `react-native-builder-bob` or `react-native-image-picker` which uses bob. I just saw your post/issue as one of the few who experienced this this problem over the past few days.

Also, it feels a bit weird in my case to just add `csstype` as a devDependency is my project as doesn't rely directly on this.

**Comment by mattijsf** [comment]
Found the culprit: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49713

**Comment by satya164** [comment]
@mattijsf yea `csstype` should be a dependency of the react types, not an issue in bob or image picker.
