### ISSUE TITLE
Trying to use the latest versions of react and react-native fails

### ISSUE THREAD

**Issue by daihovey** [callstack/react-native-builder-bob#181]
## Environment

MacOS

## Description

Trying to bump the `react` and `react-native` versions to the latest fails
## Reproducible Demo

change both `package.json`'s to

```
    "react": "17.0.1",
    "react-native": "0.64.1",
```

```
yarn
yarn run v1.22.5
$ yarn example && yarn && yarn pods
$ yarn --cwd example
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 1 files in src with babel
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 1 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
✔ Wrote definition files to lib/typescript
$ cd example && pod-install --quiet
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
1.10.1
> pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] The `react-native-nft-components` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - 
Aborting run
An unexpected error was encountered. Please report it as a bug:
CocoaPodsError: Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 1
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
    at CocoaPodsPackageManager._installAsync (/node_modules/pod-install/build/index.js:2:92213)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CocoaPodsPackageManager.installAsync (/node_modules/pod-install/build/index.js:2:90176)
    at async runAsync (/node_modules/pod-install/build/index.js:2:106198)
    at async /node_modules/pod-install/build/index.js:2:106284 {
  code: 'COMMAND_FAILED',
  cause: Error: pod exited with non-zero code: 1
      at ChildProcess.h (/node_modules/pod-install/build/index.js:2:1073)
      at Object.onceWrapper (events.js:421:26)
      at ChildProcess.emit (events.js:314:20)
      at maybeClose (internal/child_process.js:1047:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
      ...
      at Object.spawnAsync [as default] (/node_modules/pod-install/build/index.js:2:558)
      at CocoaPodsPackageManager._runAsync (/node_modules/pod-install/build/index.js:2:92995)
      at CocoaPodsPackageManager._installAsync (/node_modules/pod-install/build/index.js:2:90499)
      at CocoaPodsPackageManager.installAsync (/node_modules/pod-install/build/index.js:2:90187)
      at runAsync (/node_modules/pod-install/build/index.js:2:106206)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async /node_modules/pod-install/build/index.js:2:106284 {
    pid: 96308,
    output: [
      '',
      'Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1\n'
    ],
    stdout: '',
    stderr: 'Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1\n',
    status: 1,
    signal: null
  },
  isPackageManagerError: true
}

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Alexufo** [comment]
only "react-native": "0.63.4", supported :-(
