### ISSUE TITLE
Cannot run android example

### ISSUE THREAD

**Issue by Janaka-Steph** [callstack/react-native-builder-bob#299]
## Environment

Mac m1
create-react-native-library: 0.24.3

## Description

Creating new project with `npx create-react-native-library@latest gdk-android`
Run `yarn`
Run `yarn example android`

Get errors:
- Plugin with id 'com.facebook.react' not found.
- compileSdkVersion is not specified

```
▶ yarn example android                                                                                            
yarn run v1.22.19
$ yarn --cwd example android
$ react-native run-android
warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
info JS server already running.
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/janaka/Desktop/gdk/gdk-android/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'GdkAndroidExample'.
> Plugin with id 'com.facebook.react' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'GdkAndroidExample'.
> compileSdkVersion is not specified.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/janaka/Desktop/gdk/gdk-android/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'GdkAndroidExample'.
> Plugin with id 'com.facebook.react' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'GdkAndroidExample'.
> compileSdkVersion is not specified.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (/Users/janaka/Desktop/gdk/gdk-android/example/node_modules/execa/index.js:174:9)
    at /Users/janaka/Desktop/gdk/gdk-android/example/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/janaka/Desktop/gdk/gdk-android/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/janaka/Desktop/gdk/gdk-android/example/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ravisharnagat** [comment]
I am also facing the same issue.

**Comment by satya164** [comment]
Can you provide more details such as which options you chose?

**Comment by Janaka-Steph** [comment]
I have selected Turbo module with backward compat (experimental) also
