### ISSUE TITLE
**ERROR** Failed to apply patch for package react-native at path

### ISSUE THREAD

**Issue by hannojg** [callstack/react-native-builder-bob#316]
### Description

When just setting up a new library with the new arch + backwards compatible, on running `yarn` after setup the following error is thrown:

```log
Last login: Sat Oct 29 13:10:06 on ttys006

~ via ⬢ v16.15.1 
➜ cd Documents/GitHub 

~/Documents/GitHub 
➜ npx create-react-native-library@latest react-native-skia-skottie
Need to install the following packages:
  create-react-native-library@latest
Ok to proceed? (y) y
✔ What is the name of the npm package? … LIB-NAME
✔ What is the description for the package? … XXX
✔ What is the name of package author? … Hanno J. Gödecke
✔ What is the email address for the package author? … XXX
✔ What is the URL for the package author? … XXX
✔ What is the URL for the repository? … XXX
✔ What type of library do you want to develop? › Turbo module with backward compat (experimental)
✔ Which languages do you want to use? › Java & Objective-C
✔ Project created successfully at XXX

Get started with the project:

  $ yarn

Run the example app on iOS:

  $ yarn example ios

Run the example app on Android:

  $ yarn example android

Good luck!

~/Documents/GitHub took 4m 29s 
➜ cd LIB-NAME

react-native-skia-skottie on  main is 📦 v0.1.0 via ⬢ v16.15.1 
➜ yarn
yarn run v1.22.19
warning ../../../package.json: No license field
$ yarn example && yarn install && yarn example pods
warning ../../../package.json: No license field
$ yarn --cwd example
warning ../../../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ patch-package
patch-package 6.5.0
Applying patches...

**ERROR** Failed to apply patch for package react-native at path
  
    node_modules/react-native

  This error was caused because react-native has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run 

    patch-package react-native

  Info:
    Patch file: patches/react-native+0.70.0.patch
    Patch was made for version: 0.70.0
    Installed version: 0.70.4

---
patch-package finished with 1 error(s).
warning ../../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @arkweid/lefthook@0.7.7: @arkweid/lefthook has been renamed to @evilmartians/lefthook, please upgrade to it. You also can use @evilmartians/lefthook-installer
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > metro-react-native-babel-transformer@0.72.3" has unmet peer dependency "@babel/core@*".
warning "react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 2 files in src with babel
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 2 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
✔ Wrote definition files to lib/typescript
warning ../../../package.json: No license field
$ yarn --cwd example pods
warning ../../../../package.json: No license field
$ pod-install --quiet
Traceback (most recent call last):
	4: from /Users/hannogodecke/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
	3: from /Users/hannogodecke/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
	2: from /Users/hannogodecke/.rvm/rubies/ruby-2.7.5/bin/pod:23:in `<main>'
	1: from /Users/hannogodecke/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
/Users/hannogodecke/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
› Attempting to install CocoaPods CLI with Gem
Fetching cocoapods-1.11.3.gem
Successfully installed cocoapods-1.11.3
1 gem installed
› Successfully installed CocoaPods CLI with Gem
> pod install
Couldn't install Pods. Updating the Pods project and trying again...
> pod install --repo-update
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 1
/Users/hannogodecke/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
	from /Users/hannogodecke/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
	from /Users/hannogodecke/.rvm/gems/ruby-2.7.5/bin/pod:23:in `<main>'
	from /Users/hannogodecke/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
	from /Users/hannogodecke/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

See above

### Environment

info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 877.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/hannogodecke/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Patch 1 Chipmunk 2021.2.1 Patch 1
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /Users/hannogodecke/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by satya164** [comment]
The patch isn't needed in the latest version of React Native anymore so you can safely remove it. This will be fixed in the next release of create react native library.
