### ISSUE TITLE
bob build failure in windows

### ISSUE THREAD

**Issue by KiruthikaJeyashankar** [callstack/react-native-builder-bob#380]
### Description

When running `yarn` command, I get bob build failure in my windows machine while this issue is not reproducible in mac machine.
(`bob build` is our prepare script in the package.json)
 
Attaching the error details below,
```
PS <project_path>> yarn
yarn run v1.22.19
$ yarn example && yarn install && yarn example pods
$ yarn --cwd example
[1/4] Resolving packages...
success Already up-to-date.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib\commonjs
ℹ Compiling 3 files in src with babel
✔ Wrote files to lib\commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib\module
ℹ Compiling 3 files in src with babel
✔ Wrote files to lib\module
ℹ Building target typescript
ℹ Cleaning up previous build at lib\typescript
ℹ Generating type definitions with tsc
✔ Wrote definition files to lib\typescript
ℹ Building target aar
ℹ Cleaning up previous build at lib\aar
ℹ Assembling Android project in android with gradle
ℹ Creating new output directory at lib\aar
ℹ Copying AAR from android\build\outputs\aar\android-debug.aar to lib\aar\android-debug.aar
ℹ Creating AAR Gradle file at lib\aar\build.gradle
ℹ Creating new support output directory at lib\aar\support
ℹ Using Jetifier to convert AAR from AndroidX to Support AAR at lib\aar\support\android-debug.aar
bob build

build files for publishing

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

<ref *1> Error: spawnSync <project_path>\node_modules\.bin\jetifier-standalone ENOENT
    at Object.spawnSync (node:internal/child_process:1119:20)
    at spawnSync (node:child_process:847:24)
    at execFileSync (node:child_process:890:15)
    at jetifier (<project_path>\node_modules\react-native-builder-bob\lib\utils\jetifier.js:33:37)
    at async build (<project_path>\node_modules\react-native-builder-bob\lib\targets\aar.js:73:5)
    at async Object.handler (<project_path>\node_modules\react-native-builder-bob\lib\index.js:349:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync <project_path>\\node_modules\\.bin\\jetifier-standalone',
  path: '<project_path>\\node_modules\\.bin\\jetifier-standalone',
  spawnargs: [
    '-i',
    '<project_path>\\lib\\aar\\android-debug.aar',
    '-o',
    '<project_path>\\lib\\aar\\support\\android-debug.aar',
    '-r'
  ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Packages

- [ ] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

```
"react-native-builder-bob": {
    "source": "src",
    "output": "lib",
    "targets": [
      "commonjs",
      "module",
      [
        "typescript",
        {
          "project": "tsconfig.build.json"
        }
      ],
      [
        "aar",
        {
          "reverseJetify": true,
          "androidBundleName": "android-debug.aar"
        }
      ]
    ]
  }
```

### Environment

**System**

- OS: Windows 10.0.14393.5582
- System type: 64-bit operating system, x-64 based processor

**Tools**

- Node: 16.19.0
- npm: 8.19.3
- yarn: 1.22.19

**SDK**

- Android SDK build tools: 29.0.2, 29.0.3, 30.0.2, 33.0.2

**npm packages**

- "react": "18.1.0"
- "react-native": "0.70.6"
- "react-native-builder-bob": "^0.20.0" => 0.20.1
- java: openjdk version "11.0.18" 2023-01-17
-./gradlew: Gradle 7.4

**Comment by satya164** [comment]
Closing since we don't include jetifier and AAR support anymore.
