### ISSUE TITLE
Usage Error: Unsupported package manager specification

### ISSUE THREAD

**Issue by qsalatiel** [callstack/react-native-builder-bob#436]
### Steps to reproduce
1. Run `npx create-react-native-library@latest awesome-lib`
2. Go through the wizard with the selected options
3. Run `cd awesome-lib`
4. Run `yarn`

### Error:
```
Usage Error: Unsupported package manager specification (^yarn@1.22.15,^yarn,1.22.15)

$ yarn ...
```

If I remove the line `   "packageManager": "^yarn@1.22.15",` in the package.json the dependencies installation works but after if I try to run `yarn example web`  I get another error:

```
Internal Error: ENOENT: no such file or directory, lstat '/Users/salatielqueiroz/personal/awesome-lib/example/example'
    at Object.realpathSync (node:fs:2552:7)
    at NodeFS.realpathSync (/Users/salatielqueiroz/personal/awesome-lib/.pnp.cjs:17314:45)
    at makeCallSync.archivePath.archivePath (/Users/salatielqueiroz/personal/awesome-lib/.pnp.cjs:19434:26)
    at ZipOpenFS.makeCallSync (/Users/salatielqueiroz/personal/awesome-lib/.pnp.cjs:19934:14)
    at ZipOpenFS.realpathSync (/Users/salatielqueiroz/personal/awesome-lib/.pnp.cjs:19433:17)
    at VirtualFS.realpathSync (/Users/salatielqueiroz/personal/awesome-lib/.pnp.cjs:19183:26)
    at PosixFS.realpathSync (/Users/salatielqueiroz/personal/awesome-lib/.pnp.cjs:18934:41)
    at NodePathFS.realpathSync (/Users/salatielqueiroz/personal/awesome-lib/.pnp.cjs:18934:41)
    at i (/Users/salatielqueiroz/.cache/node/corepack/yarn/3.6.1/yarn.js:446:12005)
    at async t (/Users/salatielqueiroz/.cache/node/corepack/yarn/3.6.1/yarn.js:446:10283)
```

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

✔ What is the name of the npm package? … react-native-awesome-lib
✔ What is the description for the package? … super awesome lib
✔ What is the name of package author? … qsalatiel
✔ What is the email address for the package author? … *******@gmail.com
✔ What is the URL for the package author? … https://github.com/qsalatiel
✔ What is the URL for the repository? … https://github.com/qsalatiel/react-native-awesome-lib
✔ What type of library do you want to develop? › JavaScript library
✔ Project created successfully at awesome-lib!

### Environment

- macOS Monterey (v12.6) Apple M1
- Node v18.12.1
- Yarn v3.6.1

**Comment by dFelinger** [comment]
Same error.
Just use node version from .nvmrc

**Comment by satya164** [comment]
Fixed in https://github.com/callstack/react-native-builder-bob/commit/f90ce8920c5c8ce6d4904f9b47200d18270d067a
