### ISSUE TITLE
Build fails for typescript target in Windows

### ISSUE THREAD

**Issue by stanleyugwu** [callstack/react-native-builder-bob#479]
### Description

I am creating a js-only react native library with `create-react-native-library` and `bob build` is my prepack script in my project. When I run `yarn prepack` build succeeds for commonjs and module targets but fails for typescript with the following error:

```
yarn run v1.22.19
warning ..\package.json: No license field
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib\commonjs
ℹ Compiling 19 files in src with babel
✔ Wrote files to lib\commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib\module
ℹ Compiling 19 files in src with babel
✔ Wrote files to lib\module
ℹ Building target typescript
ℹ Cleaning up previous build at lib\typescript
ℹ Generating type definitions with tsc
✖ Failed to build definition files.
bob build

build files for publishing

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: Failed to build definition files.
    at build (C:\Users\USER\Desktop\Devvie\coding\projects\mobile\react-native-bottom-sheet\node_modules\react-native-builder-bob\lib\targets\typescript.js:155:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (C:\Users\USER\Desktop\Devvie\coding\projects\mobile\react-native-bottom-sheet\node_modules\react-native-builder-bob\lib\index.js:379:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Packages

- [ ] create-react-native-library
- [X] react-native-builder-bob

### Selected options

```
"react-native-builder-bob": {
    "source": "src",
    "output": "lib",
    "targets": [
      "commonjs",
      "module",
      [
        "typescript",
        {
          "project": "tsconfig.build.json"
        }
      ]
    ]
  }
```

### Environment

```
System:
  OS: Windows 10 10.0.19044
Binaries:
  Node:
    version: 20.6.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.1.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
IDEs:
  Android Studio: AI-213.7172.25.2113.9014738
  Visual Studio: Not Found
Languages:
  Java: 16.0.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by satya164** [comment]
Can you provide a link to the project with the issue?

**Comment by stanleyugwu** [comment]
Sorry, this skipped my mind. Here's the repo of the project with the issue incase anything can still be done.

https://github.com/stanleyugwu/react-native-bottom-sheet
