### ISSUE TITLE
EMFILE error

### ISSUE THREAD

**Issue by 21522217** [callstack/react-native-builder-bob#491]
### Description

Error: [BABEL]: EMFILE: too many open files, open 'D:\source-code\do-an-1\mobile\eda\node_modules\@babel\plugin-transform-destructuring\lib\index.js' (While processing: D:\source-code\do-an-1\mobile\eda\node_modules\@babel\preset-env\lib\index.js)
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:18)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\source-code\do-an-1\mobile\eda\node_modules\@babel\preset-env\lib\available-plugins.js:30:37)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\source-code\do-an-1\mobile\eda\node_modules\@babel\preset-env\lib\filter-items.js:10:25)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\source-code\do-an-1\mobile\eda\node_modules\@babel\preset-env\lib\index.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: -4066,
  syscall: 'open',
  code: 'EMFILE',
  path: 'D:\\source-code\\do-an-1\\mobile\\eda\\node_modules\\@babel\\plugin-transform-destructuring\\lib\\index.js'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### Packages

- [ ] create-react-native-library
- [X] react-native-builder-bob

### Selected options

in package.json

"react-native-builder-bob": {
    "source": "./",
    "output": "lib",
    "targets": [
      "commonjs",
      "module",
      "typescript"
    ]
  },
  "main": "lib\\commonjs\\index.js",
  "module": "lib\\module\\index.js",
  "react-native": "index.js",
  "types": "lib\\typescript\\index.d.ts",
  "source": "index.js",
  "files": [
    "./",
    "lib",
    "!**/__tests__",
    "!**/__fixtures__",
    "!**/__mocks__",
    "./index.ts"
  ],
  "eslintIgnore": [
    "node_modules/",
    "lib/"
  ]

### Environment

info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 5600H with Radeon Graphics         "
  Memory: 6.21 GB / 15.39 GB
Binaries:
  Node:
    version: 18.7.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: D:\source-code\do-an-1\mobile\eda\node_modules\.bin\yarn.CMD
  npm:
    version: 9.8.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.6.33815.320 (Visual Studio Community 2022)
Languages:
  Java: 11.0.16.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by atlj** [comment]
Hey, could you also provide a reproduction repo and reproduction steps?
