### ISSUE TITLE
Example app not able to resolve the library present in the parent directory #590

### ISSUE THREAD

**Issue by GuptaAman08** [callstack/react-native-builder-bob#591]
### Description

HI folks,

I just upgraded my example app as per the [link](https://react-native-community.github.io/upgrade-helper/?from=0.71.4&to=0.73.0 ). 
Gradle build worked fine but when the build gets launched in the emulator it fails with the below error.
```
error: Error: Unable to resolve module @deliverysolutions/react-native-proximity-sdk from /Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/src/App.js: @deliverysolutions/react-native-proximity-sdk could not be found within the project or in these directories:
  node_modules
  ../node_modules
  12 | import { UpdateETAScreen } from './screens/UpdateETA';
  13 | import { UpdateVehicleDetailsScreen } from './screens/UpdateVehicleDetails';
> 14 | import Proximity from '@deliverysolutions/react-native-proximity-sdk';
     |                        ^
  15 | import FlashMessage from "react-native-flash-message";
  16 | const Stack = createNativeStackNavigator();
  17 |
    at ModuleResolver.resolveDependency (/Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:138:15)
    at DependencyGraph.resolveDependency (/Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at async Promise.all (index 2)
    at async visit (/Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 0)
    at async buildSubgraph (/Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/node_modules/metro/src/DeltaBundler/buildSubgraph.js:103:3)
    at async Graph._buildDelta (/Users/rajivkulkarni/Desktop/proximity-apps/new_proximity_rn_sdk/proximity-sdk-react-native/example/node_modules/metro/src/DeltaBundler/Graph.js:157:22)
```

 For some reason, I am not able to figure out why suddenly the linking is failing.

Things i tried
- I read this official article [link](https://callstack.github.io/react-native-builder-bob/faq#why-should-i-compile-my-project-with-react-native-builder-bob), and got to know that bable.config.js, metro.config.js and react-native.config.js are the key in resolving the dependency
- Also, i tried reverting changes for these three files but no luck

Can anyone please help me understand where am going wrong.

### Packages

- [X] create-react-native-library
- [x] react-native-builder-bob

### Selected options

No options. Just ran **npm prepack** = `bob build`

### Link to repro

Its not public

### Environment

Running command **npx react-native info** in Library folder provides the below detail
```
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 87.31 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: Not Found
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2023.2 AI-232.10300.40.2321.11668458
    Xcode: 15.4/15F31d - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Running command **npx react-native info** in Example app folder provides the below details
```
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 121.95 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn: Not Found
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2024.07.01.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11668458
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/rajivkulkarni/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by atlj** [comment]
Hey, this looks more like a discussion since you've modified the generated library a lot and cannot provide a repro. Closing this in favor of https://github.com/callstack/react-native-builder-bob/discussions/590.
